# Generated by Django 5.2.6 on 2026-05-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=50)),
                ('recipe_description', models.TextField()),
                ('recipe_image', models.ImageField(upload_to='recipe_iamge')),
            ],
        ),
    ]
